### ISSUE TITLE
No international support

### ISSUE THREAD

**Issue by athe0s** [peeinears/google-gifs-chrome#1]
Google uses international domain suffixes so the extension should work on www.google.* instead of just www.google.com.

**Comment by tony-pizza** [comment]
Good catch. Unfort you can't do a wildcard TLD like that (I guess for good reason). Reference: http://stackoverflow.com/questions/16186956/how-to-load-a-content-script-on-all-google-international-pages

**Comment by tony-pizza** [comment]
Oh, just found this cool page: https://www.google.com/supported_domains. Maybe I'll rewrite to support just those.
